In [1]:
# speed test

In [3]:
#python using list
import numpy as np
import time
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()

add =[x+y for x,y in zip(list1,list2)]
print(add[0:10])
end =time.time()

print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.1075432300567627


In [4]:
l1 =[1,2,3]

In [5]:
l2 = [6,4,2]

In [6]:
list(zip(l1,l2))

[(1, 6), (2, 4), (3, 2)]

In [7]:
l1 = ["shivani","pankaj"]

In [8]:
l2 = ["gupta","bairagi"]

In [9]:
list(zip(l1,l2))

[('shivani', 'gupta'), ('pankaj', 'bairagi')]

In [10]:
#numpy using array

import numpy as np
import time
size = 1_000_000
list1 = np.array(list(range(size)))
list2 = np.array(list(range(size)))

start = time.time()

add =list1 + list2
print(add)
end =time.time()

print(end - start)

[      0       2       4 ... 1999994 1999996 1999998]
0.02893686294555664


In [11]:
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()

add = arr1 +arr2
end = time.time()

print(end - start)

0.016659259796142578


In [13]:
np.array([1,2,3,4,5 , "shiv"])

array(['1', '2', '3', '4', '5', 'shiv'], dtype='<U21')

In [17]:
#2d array
arr =np.array([[1,2,3],[4,5,6]])

In [18]:
type(arr)

numpy.ndarray

In [20]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [25]:
#python list(loop base)
list_squares = [x ** 2 for x in list1]

#numpy (vectorized)
numpy_squares = arr1 ** 2

In [30]:
arr1 =np.array([[1,2,3],[4,5,6]])

In [32]:
squared_arr1 =np.square(arr1)
print("squared array:",squared_arr1)

squared array: [[ 1  4  9]
 [16 25 36]]


In [33]:
import numpy as np

# Create a sample array
arr = np.array([1, 2, 3, 4, 5])

# Method 1: Using np.square()
squared_arr = np.square(arr)

# Method 2: Using the ** operator
squared_arr_alt = arr**2

print("Original Array:", arr)
print("Squared Array (Method 1):", squared_arr)
print("Squared Array (Method 2):", squared_arr_alt)

Original Array: [1 2 3 4 5]
Squared Array (Method 1): [ 1  4  9 16 25]
Squared Array (Method 2): [ 1  4  9 16 25]


In [35]:
!pip install numpy


[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [38]:
arr = np.array([1,3,4])

In [39]:
arr

array([1, 3, 4])

In [40]:
#3d 
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
np.ones((3,1))

array([[1.],
       [1.],
       [1.]])

In [46]:
np.full((4,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [47]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [52]:
np.linspace(0,100,5)#gap 

array([  0.,  25.,  50.,  75., 100.])

In [53]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
myarr.shape

(3, 3)

In [56]:
myarr.size

9

In [57]:
myarr.ndim # dim = dimension

2

In [58]:
myarr.dtype

dtype('int64')

In [59]:
# changing data types

In [62]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = 'float32')

In [63]:
myarr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [64]:
n = myarr.astype('float64')

In [65]:
n.dtype

dtype('float64')

In [66]:
myarr.dtype

dtype('float32')

In [67]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[6,7,8]])

In [68]:
myarr.shape

(4, 3)

In [69]:
reshaped = myarr.reshape((3,4))

In [71]:
reshaped

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 6, 7, 8]])

In [72]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [6, 7, 8]])

In [73]:
myarr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 6, 7, 8])

In [74]:
# indexing and slicing

In [75]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[6,7,8]])

In [76]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [6, 7, 8]])

In [77]:
flat = arr.flatten()

In [78]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 6, 7, 8])

In [79]:
flat[0]

np.int64(1)

In [80]:
flat[3:6]

array([4, 5, 6])

In [81]:
b = flat[3:7] #slicing

In [82]:
b

array([4, 5, 6, 7])

In [86]:
b[0]= 2222

In [87]:
b

array([2222,    5,    6,    7])

In [88]:
flat

array([   1,    2,    3, 2222,    5,    6,    7,    8,    9,    6,    7,
          8])

In [89]:
b = flat[3:7].copy()

In [92]:
b

array([444444,      5,      6,      7])

In [91]:
b[0]= 444444

In [93]:
flat #no changes in flat bbus copy kiya h 

array([   1,    2,    3, 2222,    5,    6,    7,    8,    9,    6,    7,
          8])

In [96]:
arr = np.array([1,54,33,2,45,43,22,21,4,2,6])

In [97]:
arr[[1,4,6]] #slicing

array([54, 45, 22])

In [99]:
#boolean masking
arr[arr>23]

array([54, 33, 45, 43])

In [101]:
arr = np.array([[1,2,3],[0,9,8],[4,5,6]]) #Create a 3×3 array filled with random numbers and print its shape.

In [102]:
arr

array([[1, 2, 3],
       [0, 9, 8],
       [4, 5, 6]])

In [104]:
arr.shape

(3, 3)

In [116]:
arr = np.array([1.1,2.2,3.3], dtype='int') #Convert an array of floats [1.1, 2.2, 3.3] into integers

In [117]:
arr.dtype

dtype('int64')

In [118]:
arr

array([1, 2, 3])

In [119]:
arr =np.array([1,2,3,54,65,50,33,54,34,23,44,34,43,56,21]) #Use boolean masking to filter numbers greater than 50 in an array.

In [120]:
arr

array([ 1,  2,  3, 54, 65, 50, 33, 54, 34, 23, 44, 34, 43, 56, 21])

In [121]:
arr[arr>50]

array([54, 65, 54, 56])

In [ ]:
arr = np.array([[1,2,3],[0,9,8],[4,5,6]])#Reshape a 1D array of size 9 into a 3×3 matrix.

In [133]:
arr = np.array([1,2,3,4,5,6,7,8,9]) #Reshape a 1D array of size 9 into a 3×3 matrix.

In [134]:
reshaped = arr.reshape((3,3))

In [135]:
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
arr = np.array([1,2,3,4,5,6])#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [137]:
even_number = arr[arr % 2 == 0]

In [139]:
even_number

array([2, 4, 6])

In [187]:
arr = np.array([[1,2,3],
[4,5,6],
[7,8,9]])

In [188]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [189]:
arr[0]

array([1, 2, 3])

In [190]:
arr[1]

array([4, 5, 6])

In [191]:
arr[2]

array([7, 8, 9])

In [192]:
np.sum(arr,axis=0)  #column

array([12, 15, 18])

In [193]:
np.sum(arr,axis=1) #row

array([ 6, 15, 24])

In [194]:
arr[0][1]

np.int64(2)

In [195]:
arr[0,2]

np.int64(3)

In [196]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [197]:
arr3D = np.array([
    [[1,2,3], [4,5,6]],
    
[[7,8,9], [10,11,12]]
    
])

In [198]:
print(arr3D[:,0,0])

[1 7]


In [166]:
print(arr3D[:, 0, :])


# [dept,row,column]

[[1 2 3]
 [7 8 9]]


In [168]:
arr3D[:, 0, :] = 0

In [169]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])

In [199]:


arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [200]:
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [201]:
arr[0, 1]   # Row 0, Column 1 → 2
arr[1, 2]   # Row 1, Column 2 → 6

np.int64(6)

In [202]:
arr[0]      # [1 2 3]

array([1, 2, 3])

In [203]:
arr[:, 1]   # [2 5]

array([2, 5])

In [204]:
# Axis Concept (VERY IMPORTANT ⭐)

In [205]:
[[1, 2, 3],
 [4, 5, 6]] #For 2D array Axis 0 → Vertical (columns)
# Axis 1 → Horizontal (rows)

[[1, 2, 3], [4, 5, 6]]

In [206]:
np.sum(arr, axis=0)

array([5, 7, 9])

In [207]:
# [1+4, 2+5, 3+6]  [5, 7, 9]

In [208]:
np.sum(arr, axis=1)

array([ 6, 15])

In [209]:
first_col = arr[:, 0]
print(first_col)

[1 4]


In [210]:
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


In [212]:
# Data Types in NumPy
# int32,64,float32,bool,complex64,object

In [213]:
arr = np.array([2,3,4,33,4,2])

In [217]:
arr.dtype

dtype('int64')

In [221]:
arr.astype("float32")

array([ 2.,  3.,  4., 33.,  4.,  2.], dtype=float32)

In [218]:
arr.astype("float64")

array([ 2.,  3.,  4., 33.,  4.,  2.])

In [222]:
arr.nbytes

48

In [223]:
# Complex Numbers
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr)



[1.+2.j 3.+4.j 5.+6.j]


In [224]:
# String Array
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10')  # Unicode string array
print(arr)

['apple' 'banana' 'cherry']


In [225]:
# Object Data Type
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

[{'a': 1} list([1, 2, 3]) 'hello']


In [226]:
# Broadcasting

In [227]:
arr = np.array([1, 2, 3, 4, 5])
result = []
 
# Using a loop to square each element (slow)
for num in arr:
    result.append(num ** 2)
 
print(result)  # Output: [1, 4, 9, 16, 25]

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [231]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2 
print(result)

[ 1  4  9 16 25]


In [232]:
result + 10 

array([11, 14, 19, 26, 35])

In [229]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 3 
print(result)

[  1   8  27  64 125]


In [233]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3])

In [234]:
result = arr1 + arr2 
print(result)

[[2 4 6]
 [5 7 9]]


In [237]:
data = np.array([[10,20,30], [15,25,35], [ 20, 30 , 40], [ 25,35,45], [30,40,50]])


mean = data.mean(axis = 0)


std = data.std(axis=0)

normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [247]:
arr = np.array([3,5,2,33])

In [248]:
np.mean(arr)

np.float64(10.75)

In [249]:
np.min(arr)

np.int64(2)

In [246]:
np.max(arr)

np.int64(33)

In [250]:
np.std(arr)

np.float64(12.891373084353738)

In [251]:
np.var(arr)

np.float64(166.1875)

In [252]:
np.sum(arr)

np.int64(43)

In [253]:
np.prod(arr) #mulriplt

np.int64(990)

In [254]:
np.median(arr)

np.float64(4.0)

In [256]:
np.percentile(arr,2)

np.float64(2.06)

In [257]:
np.argmin(arr)

np.int64(2)

In [258]:
np.argmax(arr)

np.int64(3)

In [259]:
np.corrcoef(arr)

np.float64(1.0)

In [260]:
np.unique(arr)

array([ 2,  3,  5, 33])

In [261]:
np.diff(arr)

array([ 2, -3, 31])

In [262]:
np.cumsum(arr)

array([ 3,  8, 10, 43])

In [264]:
np.linspace(arr,1,2)

array([[ 3.,  5.,  2., 33.],
       [ 1.,  1.,  1.,  1.]])

In [ ]:
# Create a NumPy array with values: [5, 10, 15, 20, 25] and find its shape and size

In [265]:
arr = np.array([5,10,15,20,25])

In [266]:
arr

array([ 5, 10, 15, 20, 25])

In [267]:
np.shape(arr)

(5,)

In [270]:
np.size(arr)

5

In [271]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [272]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [273]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [274]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [281]:
arr3 = np.array([10,20,30,40,50])
last_element = arr3[ 2: ,]

In [282]:
last_element

array([30, 40, 50])

In [ ]:
arr = np.array([])